### PR TITLE
Fix config report origin icon

### PR DESCRIPTION
**Pull request by sbernhard**

### CODE REVIEW

**Comment by lzap** [comment]
Yes please rebase it to something like https://github.com/theforeman/foreman_salt/pull/111/files it's now consistent.

**Comment by sbernhard** [comment]
This is a about report_origin_icon and not fact origin/icon_path.

**Comment by lzap** [comment]
Sorry, carry on!

**Comment by ares** [comment]
sorry for the delay, merging finally, thanks @sbernhard

**Pull request merged**
