### PR TITLE
Fixes #29060 - use new ImporterRegistry to register ForemanChef

### PR DESCRIPTION
**Pull request by rahulbajaj0509**

### CODE REVIEW

**Comment by rahulbajaj0509** [comment]
I wonder how the tests are passing without the correct change being merged in Foreman core! Are we really using the registry here? can you please check. @ezr-ondrej @ares

FYI, the correct change would be `::Foreman::Plugin.fact_importer_registry.register(:foreman_chef, ForemanChef::FactImporter)` incase you want to test it with that :)

**Comment by ares** [comment]
Maybe it's because this plugin has 0 tests :-)

**Comment by rahulbajaj0509** [comment]
@ares @ezr-ondrej should we get this merged?

**Comment by rahulbajaj0509** [comment]
@ares done :+1:

**Comment by ezr-ondrej** [comment]
It's a good idea to link a core PR for reference. This was introduced in theforeman/foreman#5010

**Comment by rahulbajaj0509** [comment]
@ares anything to add here?

**Pull request merged**
