### PR TITLE
Fix Error uninitialized constant ForemanChef::Engine::ForemanTasks

### PR DESCRIPTION
**Pull request by EdHurtig**
**I have not fully tested this... I just used some intuition and guessed to see if I could fix the error**

Fixes a fatal error preventing foreman from starting: uninitialized constant ForemanChef::Engine::ForemanTasks (NameError)

Full Stack Trace

```
/usr/share/foreman/vendor/ruby/1.9.1/gems/foreman_chef-0.1.3/lib/foreman_chef/engine.rb:23:in `block in <class:Engine>': uninitialized constant ForemanChef::Engine::ForemanTasks (NameError)
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
        from /usr/share/foreman/config/environment.rb:12:in `<top (required)>'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /usr/share/foreman/config.ru:3:in `block in <main>'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
        from /usr/share/foreman/config.ru:in `new'
        from /usr/share/foreman/config.ru:in `<main>'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:40:in `eval'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:40:in `parse_file'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/rack-1.4.5/lib/rack/server.rb:200:in `app'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.21/lib/rails/commands/server.rb:46:in `app'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/rack-1.4.5/lib/rack/server.rb:304:in `wrapped_app'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/rack-1.4.5/lib/rack/server.rb:254:in `start'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.21/lib/rails/commands/server.rb:70:in `start'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.21/lib/rails/commands.rb:55:in `block in <top (required)>'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.21/lib/rails/commands.rb:50:in `tap'
        from /usr/share/foreman/vendor/ruby/1.9.1/gems/railties-3.2.21/lib/rails/commands.rb:50:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

### CODE REVIEW

**Comment by ares** [comment]
First of all, thanks for the patch! I didn't see this error, so I'm wondering what's different on your setup. How did you install Foreman? Is it package based installation? Was it using foreman-installer? What were installer parameter in such case?

**Comment by ohadlevy** [comment]
@ares, in general, an engine needs to require all its gems (as they dont
get auto required by bunder when using gemspec), I assume some other place
was requiring foreman-tasks ?

**Comment by ares** [comment]
Right, that makes sense, merged as ac8a0cc51813db7efd796578d7bbe2c69e00cf25, thank you @EdHurtig, will be part of 0.1.4 release.

**Comment by EdHurtig** [comment]
Thanks @ares, For the record I installed foreman using foreman-installer, then added `gem 'foreman_chef'` to `/usr/share/foreman/Gemfile` then ran `bundle install`.  Then restarted the foreman service... which failed

**Comment by ares** [comment]
we have the plugin packaged and foreman-installer have options to install it for you (recommended way), for more details see http://www.theforeman.org/plugins/foreman_chef/0.1/#2.Installation

**Comment by EdHurtig** [comment]
Ah, I definitely should have used the installer for this.

**Pull request closed without merging**
