### PR TITLE
Fixes #21620 - Add support for optional version

### PR DESCRIPTION
**Pull request by Routhinator**

### CODE REVIEW

**Comment by Routhinator** [comment]
I give up. The bot is annoying. The code is there and ready to merge.

**Comment by ares** [comment]
@routhinator I'm sorry for the bot. It tries to tell you, that some of your commit it not named correctly. Please squash all your commits into a single one. The title of the first one is correct.

**Comment by ares** [comment]
Also please note the templates updated in your second commit should not be updated here but in a separate repo at https://github.com/theforeman/community-templates which is beign synced to this code base regularly. Thank you.

**Comment by ares** [comment]
Oh, please ignore my last comment, that applies to core only. I can also squash the commits for you on merge. Thanks, please give me some time to test it.

**Comment by ares** [comment]
Thanks, I updated the syntax so that the patch is compatible with Foreman 1.17 (under construction) and also extended the gem bootstrap method the same way, so this PR was replaced by https://github.com/theforeman/foreman_chef/pull/82

**Pull request closed without merging**
